name: Deploy to GitHub Pages

on:
  push:
    branches:
      - aj # 若主要分支名稱為 master 請改為 master
      workflow_dispatch: # 加上這行， Actions 頁面就會出現「Run workflow」手動按鈕

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 將打包出來的 dist 推送到 gh-pages 分支